image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixos-unstable
sources:
  - https://git.sr.ht/~pvsr/qpm
tasks:
  - py38: |
      cd qpm
      nix run --argstr python python38 -c pytest
  - py37: |
      cd qpm
      nix run --argstr python python37 -c pytest
  - py36: |
      cd qpm
      nix run --argstr python python36 -c pytest
