image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixos-unstable
sources:
  - https://git.sr.ht/~pvsr/qpm
tasks:
  - py38: |
      cd qpm
      ./nixos-test python38
  - py37: |
      cd qpm
      ./nixos-test python37
  - py36: |
      cd qpm
      ./nixos-test python36
