image: nixos/unstable
sources:
  - https://git.sr.ht/~pvsr/qpm
environment:
  NIX_CMD: nix --experimental-features 'nix-command flakes'
tasks:
  - build: |
      cd qpm
      $NIX_CMD build
  - format: |
      cd qpm
      $NIX_CMD develop -c -- black --diff --check qpm tests
  - mypy: |
      cd qpm
      $NIX_CMD develop -c -- python setup.py --version
      $NIX_CMD develop -c -- mypy qpm tests
  - pytest: |
      cd qpm
      $NIX_CMD develop -c -- pytest
