image: nixos/unstable
sources:
  - https://git.sr.ht/~pvsr/qpm
tasks:
  - build: |
      cd qpm
      nix build
  - format: |
      cd qpm
      nix develop - -- black --diff --check qpm tests
  - mypy: |
      cd qpm
      nix develop -c python setup.py --version
      nix develop -c mypy qpm tests
  - pytest: |
      cd qpm
      nix develop -c pytest
