image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixos-unstable
sources:
  - https://git.sr.ht/~pvsr/qpm
tasks:
  - deps: |
      cd qpm
      nix-shell --quiet --run exit
  - format: |
      cd qpm
      nix-shell --run 'black --diff --check qbpm tests'
  - mypy: |
      cd qpm
      nix-shell --run 'python setup.py --version'
      nix-shell --run 'mypy qbpm tests'
  - pytest: |
      cd qpm
      nix-shell --run pytest
