image: nixos/unstable
repositories:
  nixpkgs: https://nixos.org/channels/nixos-unstable
sources:
  - https://git.sr.ht/~pvsr/qpm
tasks:
  - py38: |
      cd qpm
      scripts/nixos-test.sh python38
  - py37: |
      cd qpm
      scripts/nixos-test.sh python37
  - py36: |
      cd qpm
      scripts/nixos-test.sh python36
