# qutebrowser basedir
[basedir]
location = "{{ basedir }}/{{ name | dashcase }}"
overwrite = false
  [basedir.dirs.config]
    [basedir.dirs.config.files."config.py"]
    link = "$XDG_CONFIG_HOME/.config/qutebrowser/config.py"

    [basedir.dirs.config.dirs."conf.d".files."ssb.py"]
    template = "ssb.py"

  [basedir.dirs.data]
    [basedir.dirs.data.files.blocked-hosts]
    link = "$XDG_DATA_HOME/qutebrowser/blocked-hosts"

[bin]
location = "{{ bin }}"
  [bin.files."{{ name | dashcase }}"]
  overwrite = false
  contents = """
#!/bin/sh
qutebrowser --basedir "{{ basedir }}/{{ name | dashcase }}" "$@"\
  """

[applications]
location = "{{ applications }}/qute-ssb"
#location = "$XDG_DATA_HOME/applications/qute-ssb"
  [applications.files."{{ name | dashcase }}.desktop"]
  overwrite = false
  template = "default.desktop"
